---
- name: Deploy to Tomcat
  hosts: localhost
  become: true
  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/webappCICD/target/webapp.war"
        dest: "/opt/tomcat/webapps/webapp.war"
      delegate_to: localhost

    - name: Stop Tomcat
      shell: "/opt/tomcat/bin/shutdown.sh"
      ignore_errors: yes

    - name: Start Tomcat
      shell: "/opt/tomcat/bin/startup.sh"
